- modules/mlflow/mlflow-fargate/README.md
Update MLFlow Fargate README with missing parameters
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
> docs: Update MLFlow Fargate README with missing parameters

- CHANGELOG.md
- modules/mlflow/mlflow-image/deployspec.yaml
- modules/mlflow/mlflow-image/requirements.in
- modules/mlflow/mlflow-image/requirements.txt
Fixes
```
Failed resources:
mlops-mlops-images-mlflow-image | 2:39:40 PM | CREATE_FAILED        | AWS::Lambda::Function       | Custom::CDKECRDeploymentbd07c930edb94112a20f03f096f53666512MiB (CustomCDKECRDeploymentbd07c930edb94112a20f03f096f53666512MiB28EAD8E4) 
Resource handler returned message: "The runtime parameter of go1.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (provided.al2023) while creating or updating functions.
❌  mlops-mlops-images-mlflow-image failed: Error: The stack named mlops-mlops-images-mlflow-image failed creation, it may need to be manually deleted from the AWS console: 
ROLLBACK_COMPLETE: Resource handler returned message: "The runtime parameter of go1.x is no longer supported for creating or updating …
```
> fix: `mlflow-image` - bump cdk and ecr deployment version to fix deprecated lambda runtimes issue

- CHANGELOG.md
- manifests/storage-modules.yaml
I'm updating the instance type for the MySQL DB after getting this message from AWS:
> Starting March 11, 2024, Amazon RDS will begin disabling the creation of Amazon RDS for MySQL, MariaDB, and PostgreSQL database instances running on M4, R4, or T2 instance types. 
> chore: Update RDS instance type

- CHANGELOG.md
- modules/mlflow/mlflow-image/requirements.in
- modules/mlflow/mlflow-image/requirements.txt
- modules/mlflow/mlflow-image/stack.py
When using `ECRDeployment` from `cdk_ecr_deployment` construct, there is a custom resource that gets deployed and uses the depcreated `go1.x` as the Lambda runtime. The latest direction is to use `al2023` images for go lang containers as the runtime.
Following is the error if we do not update the deprecated lambda runtime:
```
Resource handler returned message: "The runtime parameter of go1.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (provided.al2023) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 6a2ada3a-aea3-497a-950e-015da8886827)" (RequestToken: 8017ee62-a603-0b83-6c0e-d81e66f8eea5, HandlerErrorCode: InvalidRequest)
```
By submitting this pull request, I confirm that my …
> fixed the depcreated go1.x runtime

- CHANGELOG.md
- README.md
- manifests/deployment.yaml
- manifests/kernels-modules.yaml
- manifests/storage-modules.yaml
- modules/sagemaker/sagemaker-custom-kernel/README.md
- modules/sagemaker/sagemaker-custom-kernel/app.py
- modules/sagemaker/sagemaker-custom-kernel/coverage.ini
- modules/sagemaker/sagemaker-custom-kernel/deployspec.yaml
- modules/sagemaker/sagemaker-custom-kernel/docker/echo-kernel/Dockerfile
- modules/sagemaker/sagemaker-custom-kernel/docker/echo-kernel/README.MD
- modules/sagemaker/sagemaker-custom-kernel/modulestack.yaml
- modules/sagemaker/sagemaker-custom-kernel/pyproject.toml
- modules/sagemaker/sagemaker-custom-kernel/requirements.txt
- modules/sagemaker/sagemaker-custom-kernel/scripts/update_domain.py
- modules/sagemaker/sagemaker-custom-kernel/setup.cfg
- modules/sagemaker/sagemaker-custom-kernel/stack.py
- modules/sagemaker/sagemaker-custom-kernel/tests/test_app.py
- modules/sagemaker/sagemaker-custom-kernel/tests/test_stack.py
- modules/sagemaker/sagemaker-templates-service-catalog/templates/multi_account_basic/seed_code/build_app/ml_pipelines/training/_utils.py
- modules/sagemaker/sagemaker-templates-service-catalog/templates/multi_account_basic/seed_code/build_app/ml_pipelines/training/pipeline.py
- requirements-dev.txt
- add `sagemaker-custom-kernel` module
> feat: add `sagemaker-custom-kernel` module

- CHANGELOG.md
- modules/fmops/sagemaker-jumpstart-fm-endpoint/lib/sagemaker-jumpstart-fm-endpoint-stack.ts
- modules/sagemaker/sagemaker-custom-kernel/modulestack.yaml
- modules/sagemaker/sagemaker-endpoint/stack.py
- modules/sagemaker/sagemaker-studio/helper_constructs/sm_roles.py
- modules/sagemaker/sagemaker-studio/modulestack.yaml
- modules/sagemaker/sagemaker-templates-service-catalog/templates/multi_account_basic/pipeline_constructs/build_pipeline_construct.py
- modules/sagemaker/sagemaker-templates-service-catalog/templates/multi_account_basic/pipeline_constructs/deploy_pipeline_construct.py
- modules/sagemaker/sagemaker-templates-service-catalog/templates/multi_account_basic/seed_code/deploy_app/deploy_endpoint/deploy_endpoint_stack.py
- one-click-launch.yaml
Adding support for other AWS partitions, such as `aws-cn` and `aws-us-gov`.
> feat: Add support for other AWS partitions (cn, us-gov, etc.)

- CHANGELOG.md
- modules/sagemaker/sagemaker-custom-kernel/modulestack.yaml
- removed ECR IAM permissions from `sagemaker-custom-kernel`'s `modulestack.yaml` as ECR deployment is handled by CDK
> fix: `sagemaker-custom-kernel` module permissions

- data/mwaa/requirements/constraint-requirements.txt
- Consolidate dependabot updates on MWAA constraints file
- The only exception is `Flask-AppBuilder==4.3.11` that was downgraded to `4.3.10` due to a conflict with `apache-airflow==2.8.1`
- Tested E2E by deployment with udpated constraints (pointing to my fork's branch from requirements.txt) and DAG run
> chore: Consolidated mwaa constraints file update

- CHANGELOG.md
- modules/sagemaker/sagemaker-templates-service-catalog/templates/hf_import_models/product_stack.py
- modules/sagemaker/sagemaker-templates-service-catalog/templates/xgboost_abalone/product_stack.py
- Sagemaker templates: add bucket and model package group names as stack outputs
- This should make those values easier to find for customers using the `deploy` template
> (sagemaker templates) add bucket and model package group names as stack outputs

- CHANGELOG.md
- modules/sagemaker/sagemaker-endpoint/app.py
- modules/sagemaker/sagemaker-endpoint/coverage.ini
- modules/sagemaker/sagemaker-endpoint/pyproject.toml
- modules/sagemaker/sagemaker-endpoint/requirements.txt
- modules/sagemaker/sagemaker-endpoint/settings.py
- modules/sagemaker/sagemaker-endpoint/tests/test_app.py
- modules/sagemaker/sagemaker-endpoint/tests/test_stack.py
Refactor `sagemaker-endpoint` to use pydantic for inputs.
> chore: Refactor `sagemaker-endpoint` to use pydantic for inputs

- modules/fmops/bedrock-finetuning/deployspec.yaml
- modules/fmops/bedrock-finetuning/lib/bedrock-finetuning-stack.ts
- modules/fmops/bedrock-finetuning/package-lock.json
- modules/fmops/bedrock-finetuning/package.json
fix errors with bedrock-finetuning module deployment
> fix errors with bedrock-finetuning module deployment

- CHANGELOG.md
- manifests/fmops-qna-rag/networking-modules.yaml
- manifests/fmops-qna-rag/storage-modules.yaml
- remove explicit module manifest account/region mappings from `fmops-qna-rag`
> chore: remove explicit module manifest account/region mappings 

- manifests/storage-modules.yaml
- seedfarmer.yaml
Add `manifestValidationFailOnUnknownFields=true` to `seedfarmer.yaml`.
> chore: add manifestValidationFailOnUnknownFields=true to manifest

- .gitignore
- CHANGELOG.md
- modules/fmops/bedrock-finetuning/bin/bedrock-finetuning.ts
- modules/fmops/bedrock-finetuning/cdk.json
- modules/fmops/bedrock-finetuning/deployspec.yaml
- The inputs `BEDROCK_BASE_MODEL_ID` and `BUCKET_NAME` were not being read properly
- Also added a `cdk.json` file to clean up the deployspec command
> fix: Inputs for bedrock-finetuning module not working

- one-click-launch.yaml
- scripts/role_assume_update.py
- fixed 1-click launch template referencing old manifest
- reformatted manifest
- fixed reference to "mlops" in Python script
> fix: 1-click launch template referencing old manifest

- one-click-launch.yaml
- add missing `PRIMARY_ACCOUNT` env var for 1-click launch template
> fix: missing PRIMARY_ACCOUNT env var for 1-click launch template

- CHANGELOG.md
- modules/sagemaker/sagemaker-model-monitoring/sagemaker_model_monitoring/data_quality_construct.py
- modules/sagemaker/sagemaker-model-monitoring/sagemaker_model_monitoring/model_bias_construct.py
- modules/sagemaker/sagemaker-model-monitoring/sagemaker_model_monitoring/model_explainability_construct.py
- modules/sagemaker/sagemaker-model-monitoring/sagemaker_model_monitoring/model_quality_construct.py
- modules/sagemaker/sagemaker-templates-service-catalog/templates/model_deploy/seed_code/deploy_app/deploy_endpoint/deploy_endpoint_stack.py
`add_depends_on` which was used in the SageMaker model monitoring and service catalog modules is deprecated -- `add_dependency` should be used instead: https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk/CfnResource.html#aws_cdk.CfnResource.add_depends_on
(i think the difference is that `add_dependency` can be across nested stacks, but that isn't used in this repo.)
N/A
> Use add_dependency instead of deprecated add_depends_on.

- .github/ISSUE_TEMPLATE/missing_integ_tests_issue.md
- .github/workflows/check-integration-tests.yml
- This workflow is intended to poll our repo and its modules and create issues in the backlog for any modules that do not have integration tests.
- In the future as modules are added this will assure we are tracking that modules get integration tests
- The workflow will run on a schedule, but can also be triggered manuallly
> chore: adding workflow to check integration tests presence in modules

- modules/sagemaker/sagemaker-model-monitoring/README.md
- modules/sagemaker/sagemaker-model-monitoring/sagemaker_model_monitoring/data_quality_construct.py
- modules/sagemaker/sagemaker-model-monitoring/sagemaker_model_monitoring/model_bias_construct.py
- modules/sagemaker/sagemaker-model-monitoring/sagemaker_model_monitoring/model_explainability_construct.py
- modules/sagemaker/sagemaker-model-monitoring/sagemaker_model_monitoring/model_quality_construct.py
- modules/sagemaker/sagemaker-model-monitoring/sagemaker_model_monitoring/utils.py
Fixes redeploying SageMaker Model Monitoring. Previously if you modified a parameter then CloudFormation would error due to attempting to replace resources (via a create, then delete) using the same name. This adds a timestamp to names so that they'll be unique. Ideally we would allow CloudFormation to generate the names, but this does not seem to work -- CloudFormation is not properly waiting for the job definition to be created before attempting to access the name / propagating it to the monitoring schedule.
The downside of this approach is the monitoring stack will essentially be rebuilt for every update, even if no changes are made. This is double bad since updates will fail if any of the monitoring jobs are running. A potential solution to this could be to use a hash of the input …
> Fix redeploying SageMaker Model Monitoring module.

- CHANGELOG.md
- modules/sagemaker/sagemaker-endpoint/stack.py
Limited the length of id in the model name to 42 characters, to prevent total model name length exceeding 63 characters and causing an exception on deploy.
> limit length of id in model name to prevent model name becoming too long

- CHANGELOG.md
- modules/sagemaker/sagemaker-templates-service-catalog/templates/hf_import_models/pipeline_constructs/build_pipeline_construct.py
Added permission for get secret value for hf access token secret to prevent error when using `hf_import_models` template
> Add permission for get secret value for hf access token secret

- CHANGELOG.md
- manifests/mlflow-experiments-tracking/storage-modules.yaml
- manifests/mlops-sagemaker-multiacc/storage-modules.yaml
- manifests/mlops-sagemaker/storage-modules.yaml
- manifests/storage-modules.yaml
- Integ testing fails to clean up ECR with images. Auto-delete feature was added in IDF 1.8.0. Bumping to latest.
- [] I updated `CHANGELOG.MD` with a description of my changes
> fix: bump ecr module version to consume auto-delete images feature

- .github/workflows/module-checks-dev-requirements-change.yml
- .github/workflows/module-checks.yml
- CHANGELOG.md
- modules/eks/ray-on-eks/README.md
- updated `get-modules` workflow to only run tests against changed files in `modules/**`
- adds workflow specific to changes for `requirements-dev.txt` so all static checks are run
> chore: update module checks workflow

- modules/eks/ray-cluster/README.md
- adding submitting ray jobs from a kubernetes batch job example to the readme
- https://github.com/awslabs/aiops-modules/issues/196
> chore: update readme for `ray-cluster`

- CHANGELOG.md
- modules/sagemaker/sagemaker-templates-service-catalog/templates/finetune_llm_evaluation/seed_code/build_app/source_scripts/requirements.txt
Added accelerate as extra for transformers in finetune llm template
> Add accelerate as extra for transformers library

- CHANGELOG.md
- modules/sagemaker/sagemaker-model-package-promote-pipeline/images/zip-image/Dockerfile
- modules/sagemaker/sagemaker-model-package-promote-pipeline/sagemaker_model_package_promote_pipeline/stack.py
This removes the custom Docker image used for bundling assets in the SageMaker model package promote pipeline stack.
It is unnecessary since the [`s3_assets.Asset` construct can natively zip a directory](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_s3_assets.Asset.html#path) (emphasis mine):
> **path**: The disk location of the asset.
>
> The path should refer to one of the following:
> * A regular file or a .zip file, in which case the file will be uploaded as-is to S3.
> * *A directory, in which case it will be archived into a .zip file and uploaded to S3.*
We are already providing the directory name as the path so it'll be automatically zipped.
Related to #193 as it is removes an image/asset to pull during deployment.
By submitting this pull request, I confirm that my …
> Remove Docker bundling in SageMaker model pkg promote pipeline

- CHANGELOG.md
- modules/eks/ray-image/src/Dockerfile
- pull `ray-ml` image from AWS ECR Public to avoid pull rate limits
> fix: pull `ray-ml` image from AWS ECR Public to avoid pull rate limits

- CHANGELOG.md
- manifests/ray-on-eks/core-modules.yaml
- manifests/ray-on-eks/ray-cluster-modules.yaml
- modules/eks/ray-orchestrator/ray_orchestrator_stack.py
- modules/eks/ray-orchestrator/scripts/training-6B.py
- changed `ray-orchestrator` to not retrieve full training job logs and avoid `States.DataLimitExceeded`
- update `ray-on-eks` manifest cluster resources
> fix: orchestrator logs

- CHANGELOG.md
- data/mwaa/requirements/constraint-requirements.txt
Bump version for `mysql-connector-python` and `snowflake-connector-python` to resolve vulnerabilities. Versions were previously bumped in #259 and #260 but were downgraded in #267 due to using the [generated constraint file](https://raw.githubusercontent.com/apache/airflow/constraints-2.10.1/constraints-3.11.txt) from apache
> Update MWAA dependencies

- CHANGELOG.md
- modules/sagemaker/sagemaker-ground-truth-labeling/labeling_step_function/labeling_state_machine.py
Fixes:
```
Resource handler returned message: "Invalid Logging Configuration: The CloudWatch Logs Resource Policy size was exceeded. We suggest prefixing your CloudWatch log group name with /aws/vendedlogs/states/. (Service: Sfn, Status Code: 400, Request ID: <REDACTED>) (SDK Attempt Count: 1)" (RequestToken: <REDACTED>, HandlerErrorCode: InvalidRequest)
```
> fix: ground truth log group name

- CHANGELOG.md
- manifests/mlops-sagemaker/deployment.yaml
- manifests/mlops-sagemaker/kernels-modules.yaml
- modules/sagemaker/sagemaker-custom-kernel/requirements.txt
- modules/sagemaker/sagemaker-studio/deployspec.yaml
- requirements.txt
- updated seedfarmer version (WARNING: uses AL2023 base image)
- set base image as AL2023 explicitly
- remove gettext-base dependency from `sagemaker-studio` module (fixes install with AL2023 base image)
- fix add explicit boto3 dependency to `sagemaker-custom-kernels` module
- changelog
> chore: update seedfarmer version & set base image to AL2023

- .github/workflows/check-integration-tests.yml
Potential fix for [https://github.com/awslabs/aiops-modules/security/code-scanning/7](https://github.com/awslabs/aiops-modules/security/code-scanning/7)
To resolve this, add a minimal `permissions` block to the `get-modules` job, specifying `contents: read`. This ensures the GITHUB_TOKEN used in the job has only the minimum necessary permission to read repository contents, preventing any accidental or malicious write access.
Specifically, edit the `.github/workflows/check-integration-tests.yml` file:
- Locate the `get-modules` job definition (starts at line 9).
- Add the following block between lines 10 (`name: Get Modules`) and 11 (`runs-on: ubuntu-latest`):
```yaml
permissions:
contents: read
```
No additional imports or method changes are needed.
_Suggested fixes powered by Copilot …
> fix: Code scanning alert no. 7: Workflow does not contain permissions
