awslabs/aiops-modules

- README.md
- modules/mlflow/mlflow-fargate/README.md
- modules/mlflow/mlflow-image/README.md
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
> chore: update readmes

- CHANGELOG.md
- manifests/mlflow-modules.yaml
- modules/mlflow/mlflow-fargate/README.md
- modules/mlflow/mlflow-fargate/app.py
- modules/mlflow/mlflow-fargate/stack.py
- modules/mlflow/mlflow-fargate/tests/test_stack.py
- https://github.com/awslabs/mlops-modules/issues/8
> feat: `mlflow-fargate` - add efs removal policy

- CHANGELOG.md
- modules/sagemaker/sagemaker-templates-service-catalog/templates/multi_account_basic/pipeline_constructs/deploy_pipeline_construct.py
- modules/sagemaker/sagemaker-templates-service-catalog/templates/multi_account_basic/product_stack.py
- modules/sagemaker/sagemaker-templates-service-catalog/templates/multi_account_basic/seed_code/deploy_app/config/constants.py
- modules/sagemaker/sagemaker-templates-service-catalog/templates/multi_account_basic/seed_code/deploy_app/deploy_endpoint/deploy_endpoint_stack.py
> chore: Remove AmazonSageMakerFullAccess from Sagemaker template

- CHANGELOG.md
- modules/sagemaker/sagemaker-endpoint/app.py
- modules/sagemaker/sagemaker-endpoint/stack.py
- modules/sagemaker/sagemaker-endpoint/tests/test_stack.py
Remove `AmazonSageMakerFullAccess` from `sagemaker-endpoint` module.
> Remove AmazonSageMakerFullAccess from sagemaker-endpoint

- CHANGELOG.md
- examples/manifests/sagemaker-endpoints-modules.yaml
- modules/sagemaker/sagemaker-endpoint/README.md
- modules/sagemaker/sagemaker-endpoint/app.py
- modules/sagemaker/sagemaker-endpoint/stack.py
- modules/sagemaker/sagemaker-endpoint/tests/test_stack.py
> feat: add managed autoscaling config to sagemaker endpoint module

- examples/manifests/sagemaker-hugging-face.yml
- manifests/fmops-modules.yaml
- modules/fmops/sagemaker-hugging-face-endpoint/README.md
- modules/fmops/sagemaker-hugging-face-endpoint/index.ts
- modules/fmops/sagemaker-hugging-face-endpoint/lib/sagemaker-hugging-face-endpoint-stack.ts
- modules/fmops/sagemaker-hugging-face-endpoint/test/sagemaker-hugging-face-endpoint.test.ts
- Add access token support to HuggingFace module
- Move deployment manifest for this module to `examples`
> fix: Add access token support to HuggingFace module

- manifests/mlops-sagemaker-multiacc/deployment.yaml
- manifests/mlops-sagemaker-multiacc/kernels-modules.yaml
- manifests/mlops-sagemaker-multiacc/networking-modules.yaml
- manifests/mlops-sagemaker-multiacc/sagemaker-studio-modules.yaml
- manifests/mlops-sagemaker-multiacc/sagemaker-templates-modules.yaml
- manifests/mlops-sagemaker-multiacc/storage-modules.yaml
- modules/sagemaker/sagemaker-templates-service-catalog/templates/model_deploy/pipeline_constructs/deploy_pipeline_construct.py
- modules/sagemaker/sagemaker-templates-service-catalog/templates/model_deploy/product_stack.py
- Fixed issue with x-acc access to pipeline bucket
- Added multi-acc manifest example
> fix: Model deploy x-acc pipeline permissions & add multi-acc manifest

- CHANGELOG.md
- manifests/mlops-sagemaker-multiacc/deployment.yaml
- modules/sagemaker/sagemaker-templates-service-catalog/templates/model_deploy/product_stack.py
> fix: multiacc manifest paths

- CHANGELOG.md
- manifests/mlflow-experiments-tracking/storage-modules.yaml
- modules/mlflow/mlflow-fargate/stack.py
- modules/mlflow/mlflow-image/stack.py
chore: adding some missing auto_delete attributes
> chore: adding some missing auto_delete attributes

- CHANGELOG.md
- manifests/mlflow-experiments-tracking/storage-modules.yaml
- manifests/mlops-sagemaker-multiacc/storage-modules.yaml
- manifests/mlops-sagemaker/storage-modules.yaml
- updating `storage/ecr` module to latest pending `v1.8.0` of IDF
- Integration Testing Fixes
> chore: updating `storage/ecr` module to latest pending `v1.8.0` of IDF

- CHANGELOG.md
- manifests/mlflow-experiments-tracking/storage-modules.yaml
- manifests/mlops-sagemaker-multiacc/storage-modules.yaml
- manifests/mlops-sagemaker/storage-modules.yaml
- manifests/storage-modules.yaml
- [] I verified that my code deploys successfully using `seedfarmer apply`
> chores: add ecr image scan on push

- .github/workflows/one-click-template-lint.yml
- one-click-launch.yaml
- rename `mlops` to `aiops`
- Add cfn_nag scanner for the template
> chore: rename mlops to aiops in the 1-click launch template

- modules/fmops/qna-rag/requirements.txt
- modules/mlflow/mlflow-fargate/requirements.txt
- modules/sagemaker/sagemaker-templates-service-catalog/requirements.in
- modules/sagemaker/sagemaker-templates-service-catalog/requirements.txt
- upgrade `urllib3` to resolve vulnerability
> chore: upgrade `urllib3` to resolve vulnerability

- .github/workflows/mwaa-requirements.check.yml
- CHANGELOG.md
- data/mwaa/requirements/constraint-requirements.txt
- data/mwaa/requirements/requirements.txt
- fix dependency issues when installing DAGs
- added a GitHub workflow to ensure the requirements and constraints all stay compatible
> fix: dependency issues in DAGs

- CHANGELOG.md
- DEPLOYMENT.md
- README.md
- modules/eks/ray-on-eks/deployspec.yaml
- modules/examples/airflow-dags/README.md
- modules/examples/airflow-dags/stack.py
- modules/examples/event-bus/README.md
- modules/fmops/bedrock-finetuning/README.md
- modules/fmops/bedrock-finetuning/src/lambda-functions/modelFinetuningLambdaCode.py
- modules/fmops/qna-rag/README.md
- modules/fmops/sagemaker-hugging-face-endpoint/lib/sagemaker-hugging-face-endpoint-stack.ts
- modules/fmops/sagemaker-jumpstart-fm-endpoint/lib/sagemaker-jumpstart-fm-endpoint-stack.ts
- modules/sagemaker/sagemaker-custom-kernel/README.md
- modules/sagemaker/sagemaker-model-package-group/README.md
- modules/sagemaker/sagemaker-model-package-group/sagemaker_model_package_group/stack.py
- modules/sagemaker/sagemaker-model-package-promote-pipeline/README.md
- modules/sagemaker/sagemaker-model-package-promote-pipeline/sagemaker_model_package_promote_pipeline/seed_code/stack/stack.py
- modules/sagemaker/sagemaker-model-package-promote-pipeline/sagemaker_model_package_promote_pipeline/stack.py
- modules/sagemaker/sagemaker-notebook/README.md
- modules/sagemaker/sagemaker-studio/scripts/delete-domains.py
- modules/sagemaker/sagemaker-studio/scripts/delete_efs.py
- modules/sagemaker/sagemaker-templates-service-catalog/README.md
- modules/sagemaker/sagemaker-templates-service-catalog/templates/hf_import_models/product_stack.py
- modules/sagemaker/sagemaker-templates-service-catalog/templates/hf_import_models/seed_code/build_app/ml_pipelines/README.md
- modules/sagemaker/sagemaker-templates-service-catalog/templates/model_deploy/pipeline_constructs/deploy_pipeline_construct.py
- modules/sagemaker/sagemaker-templates-service-catalog/templates/model_deploy/seed_code/deploy_app/tests/integration_tests/endpoint_test.py
- modules/sagemaker/sagemaker-templates-service-catalog/templates/xgboost_abalone/seed_code/build_app/README.md
No-op that corrects spelling errors found while refactoring some code.
N/A
I have not verified these changes, all are in comments, READMEs, or strings. Please verify this as a reviewer.
> Fix-up some spelling errors.

- CHANGELOG.md
- manifests/fmops-qna-rag/storage-modules.yaml
- fix opensearch removal policy 
- integration test issue remediation 
> fix opensearch removal policy

- .github/workflows/check-integration-tests.yml
- update workflow to only run once a day to avoid intermittent rate limit issues with our other repos
> chore: update workflow to only run once a day

- CHANGELOG.md
- one-click-launch.yaml
> chore: update one-click template

- CHANGELOG.md
- data/ray/ray-cluster.autoscaler.yaml
- modules/eks/ray-on-eks/app.py
- modules/eks/ray-on-eks/ray_stack.py
- modules/eks/ray-on-eks/rbac_stack.py
- modules/eks/ray-on-eks/tests/test_stack.py
> fix: add service account to kuberay

- CHANGELOG.md
- modules/sagemaker/sagemaker-templates-service-catalog/templates/finetune_llm_evaluation/seed_code/build_app/README.md
- modules/sagemaker/sagemaker-templates-service-catalog/templates/xgboost_abalone/seed_code/build_app/README.md
Fixes up some docs from changes made in #148. (It was missed in that PR.)
> Update SageMaker service catalog template docs to match code.

- CHANGELOG.md
- modules/sagemaker/sagemaker-studio/stack.py
Added permission for SM studio to describe apps when domain resource isolation is enabled
> Add permission for SM studio to describe apps

- manifests/ray-on-eks/README.md
> chore: upd training script in the docs

- .github/workflows/module-checks.yml
- modules/eks/ray-operator/tests/test_app.py
- modules/eks/ray-operator/tests/test_stack.py
Ensure tests for *all* changed modules run, not just the first one.
`$ALL_CHANGED_FILES` contains a space-separated list of changed files, when piped into `cut` this resulted in only returning the results of the first changed file.
N/A, regression from #203. Port of awslabs/idf-modules#281.
> Run CI on all changed modules, not just the first one.

- CONTRIBUTING.md
> fix the project name in the contributor

- CHANGELOG.md
- examples/manifests/networking-modules.yaml
- manifests/bedrock-finetuning-sfn/networking-modules.yaml
- manifests/fine-tuning-6b/base-modules.yaml
- manifests/fine-tuning-6b/core-modules.yaml
- manifests/fine-tuning-6b/integration-modules.yaml
- manifests/fmops-qna-rag/networking-modules.yaml
- manifests/fmops-qna-rag/storage-modules.yaml
- manifests/mlflow-tracking/networking-modules.yaml
- manifests/mlflow-tracking/storage-modules.yaml
- manifests/mlops-sagemaker-multiacc/networking-modules.yaml
- manifests/mlops-sagemaker-multiacc/storage-modules.yaml
- manifests/mlops-sagemaker/networking-modules.yaml
- manifests/mlops-sagemaker/storage-modules.yaml
- manifests/mwaa-ml-training/mwaa-modules.yaml
- manifests/mwaa-ml-training/networking-modules.yaml
- manifests/ray-on-eks/base-modules.yaml
- manifests/ray-on-eks/core-modules.yaml
- manifests/ray-on-eks/integration-modules.yaml
> chore: update idf module versions to 1.12.0

- CHANGELOG.md
- modules/sagemaker/sagemaker-templates-service-catalog/templates/finetune_llm_evaluation/product_stack.py
- modules/sagemaker/sagemaker-templates-service-catalog/templates/xgboost_abalone/product_stack.py
> fix: enforce ssl

- .github/workflows/snyk.yml
- CHANGELOG.md
- add snyk security scan workflow
> feat: add snyk

- modules/sagemaker/sagemaker-templates-service-catalog/templates/finetune_llm_evaluation/seed_code/build_app/source_scripts/requirements.txt
- update outdated transformers library
> fix: update transformers

- CHANGELOG.md
- modules/sagemaker/sagemaker-studio/helper_constructs/sm_roles.py
Fixes:
```
> aws sagemaker describe-domain  --domain-id <REDACTED>
...
PermissionError: SageMaker is unable to use your associated execution role [arn:aws:iam::<REDACTED>] to describe image version. Verify that your associated execution role has permission for 'sagemaker:DescribeImageVersion'.,
```
> fix: domain `UpdateFailed ` status
